networks:
  loki:
  traefik:
    external: true

services:
  loki:
    image: grafana/loki:latest
    # ports:
      # - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.zzbyte.dev`)"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /Users/zz_mm/Desktop/loki:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
      - GF_SERVER_DOMAIN=grafana.zzbyte.dev
      - GF_SERVER_ROOT_URL=https://grafana.zzbyte.dev
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    # ports:
      # - "3000:3000"
    networks:
      - loki
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.zzbyte.dev`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.services.grafana.loadbalancer.server.scheme=http"
      - "traefik.http.services.grafana.loadbalancer.passhostheader=true"
